# Generated by Django 4.2.14 on 2024-08-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_task.member'),
        ),
    ]
